import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
print("\n========== TITANIC DATASET ANALYSIS ==========\n")
print("1. First 5 Rows\n")
print(df.head())
print("\n2. Dataset Shape\n")
print(df.shape)
print("\n3. Columns\n")
print(df.columns)
print("\n4. Data Types\n")
print(df.dtypes)
print("\n5. Missing Values\n")
print(df.isnull().sum())
print("\n6. Statistical Summary\n")
print(df.describe())
print("\n7. Survival Count\n")
print(df["Survived"].value_counts())
print("\n8. Survival Percentage\n")
survival_percentage = (
    df["Survived"].value_counts(normalize=True) * 100
)
print(survival_percentage)
print("\n9. Gender-based Survival\n")
gender_survival = df.groupby("Sex")["Survived"].mean()
print(gender_survival)
print("\n10. Passenger Class Survival\n")
class_survival = df.groupby("Pclass")["Survived"].mean()
print(class_survival)
print("\n========== ANALYSIS COMPLETED ==========")